version: "3.8"

services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Enable or disable tests during build
        RUN_TESTS: ${RUN_TESTS:-false}
    container_name: ${CONTAINER_NAME:-coinbase-agent}
    ports:
      - "${PORT:-3000}:3000"
      - "${WEBSOCKET_PORT:-3001}:3001"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CDP_API_KEY_NAME=${CDP_API_KEY_NAME}
      - CDP_API_KEY_PRIVATE_KEY=${CDP_API_KEY_PRIVATE_KEY}
      - PORT=${PORT:-3000}
      - WEBSOCKET_PORT=${WEBSOCKET_PORT:-3001}
      - WEBSOCKET_URL=${WEBSOCKET_URL}
      - AGENT_MODE=${AGENT_MODE:-http}
      - MODEL=${MODEL:-gpt-4o-mini}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
    # Add explicit volumes for .env file to ensure variables are available
    volumes:
      - ./.env:/app/.env:ro
    command: sh -c "yarn install && yarn dev"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-3000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
